using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Silicons.DogBorgs;
using Content.Shared._Floof.Silicons.DogBorgs.Components;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Floof.Silicons.DogBorgs;

/// <summary>
///     Menu used by DogBorgs to select their type.
/// </summary>
/// <seealso cref="DogBorgSelectTypeBui"/>
/// <seealso cref="DogBorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class DogBorgSelectTypeMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    private DogBorgTypePrototype? _selectedBorgType;

    public event Action<ProtoId<DogBorgTypePrototype>>? ConfirmedBorgType;

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public DogBorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var group = new ButtonGroup();
        foreach (var borg in _protoMan.EnumeratePrototypes<DogBorgTypePrototype>().OrderBy(PrototypeName))
        {
            var button = new Button()
            {
                Text = PrototypeName(borg),
                Group = group,
            };
            button.OnPressed += _ =>
            {
                _selectedBorgType = borg;
                UpdateInformation(borg);
            };
            SelectionsContainer.AddChild(button);
        }

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null)
            return;

        ConfirmedBorgType?.Invoke(_selectedBorgType);
    }

    private void UpdateInformation(DogBorgTypePrototype borg)
    {
        _selectedBorgType = borg;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        ConfirmTypeButton.Disabled = false;

        NameLabel.Text = PrototypeName(borg);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{borg.ID}-desc");
        ChassisView.SetPrototype(borg.DummyPrototype);
    }

    private static string PrototypeName(DogBorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }
}
